["Global Settings"]
	enable = true

["Attribute 1"]
	enable = true
	display_name = "Â§4â¤ï¸ Â§fç”Ÿå‘½å€¼ Â§f| Â§4"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 2"]
	enable = true
	display_name = "Â§bğŸ›¡ï¸ Â§fæŠ¤ç”²å€¼ Â§f| Â§3"
	attribute_namespace = "minecraft"
	attribute_name = "generic.armor"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 3"]
	enable = true
	display_name = "Â§cğŸ—¡ï¸ Â§fæ”»å‡»åŠ› Â§f| Â§c"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 4"]
	enable = true
	display_name = "Â§eâš”ï¸ Â§fæ”»å‡»é€Ÿåº¦ Â§f| Â§e"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 5"]
	enable = true
	display_name = "Â§8ğŸ¹ Â§fè¿œç¨‹ä¼¤å®³% Â§f| Â§8"
	attribute_namespace = "apothic_attributes"
	attribute_name = "arrow_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 100.0

["Attribute 6"]
	enable = true
	display_name = "Â§ağŸƒ Â§fç§»åŠ¨é€Ÿåº¦% Â§f| Â§a"
	attribute_namespace = "minecraft"
	attribute_name = "generic.movement_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1000.0

["Attribute 7"]
	enable = true
	display_name = "Â§dğŸ©¸ Â§fç”Ÿå‘½æ±²å–% Â§f| Â§d"
	attribute_namespace = "apothic_attributes"
	attribute_name = "life_steal"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 100.0

["Attribute 8"]
	enable = true
	display_name = "Â§eğŸ”® Â§fæ³•åŠ›å€¼ Â§f| Â§b"
	attribute_namespace = "irons_spellbooks"
	attribute_name = "max_mana"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 9"]
	enable = true
	display_name = "Â§aâœ´ï¸ Â§fæ³•åŠ›å¼ºåº¦% Â§f| Â§b"
	attribute_namespace = "irons_spellbooks"
	attribute_name = "spell_power"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 100.0

["Attribute 10"]
	enable = true
	display_name = "Â§dğŸŒ¿ Â§fæ³•åŠ›æ¢å¤ Â§f| Â§c"
	attribute_namespace = "irons_spellbooks"
	attribute_name = "mana_regen"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 11"]
	enable = false
	display_name = "Â§fç”Ÿå‘½å€¼ï¼š"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 12"]
	enable = false
	display_name = "Â§fç”Ÿå‘½å€¼ï¼š"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 13"]
	enable = false
	display_name = "Â§fç”Ÿå‘½å€¼ï¼š"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 14"]
	enable = false
	display_name = "Â§fç”Ÿå‘½å€¼ï¼š"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 15"]
	enable = false
	display_name = "Â§9ğŸ’ª Â§fæŠ¤ç”²éŸ§æ€§ Â§f| Â§9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.armor_toughness"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

